# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DWT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DWT

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]
    pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
    pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
    pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
    pod 'react-native-maps', path: rn_maps_path
    pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
    pod 'GoogleSignIn'
#    pod 'XCDYouTubeKit', '~> 2.5'
    # Stripe
#    pod 'Stripe', '~> 14.0.0'
    # Install additional dependencies
    pod 'Firebase/Core'
#    pod 'Firebase/Auth'
#    pod 'Firebase/Crash'
#    pod 'Firebase/Database'
#    pod 'Firebase/Firestore'
    pod 'Firebase/Messaging'
#    pod 'Firebase/Performance'
#    pod 'Firebase/Storage'
    # Admobe
    pod 'Google-Mobile-Ads-SDK'
    # Facebook FBSDK
    pod 'FBAudienceNetwork', '~> 5.1.0' #facebook ads
    pod 'FacebookSDK'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    #Google Maps pods
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
    pod 'react-native-google-maps', path: rn_maps_path  # Unomment this line if you want to support GoogleMaps on iOS
    pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
    pod 'GooglePlaces'
    pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
    
#    pod 'RNPaypal', :path => '../node_modules/react-native-paypal-lib/ios'

    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

    pod 'lottie-ios', :path => '../node_modules/lottie-ios'

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

#    pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

    pod 'RNIap', :path => '../node_modules/react-native-iap'

    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  end

  # very important to have, unless you removed React dependencies for Libraries
  # and you rely on Cocoapods to manage it
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
